// Warning: generated file; your changes could be lost when a new file is generated.
#r @"..\..\packages\FSharp.Data.2.1.1\lib\net40\FSharp.Data.dll"
#r @"System.dll"
#r @"System.Core.dll"
#r @"System.Numerics.dll"
#r @"System.Xml.Linq.dll"
#r @"..\..\packages\FSharp.Charting.0.90.9\lib\net40\FSharp.Charting.dll"
#r @"System.Drawing.dll"
#r @"System.Drawing.Design.dll"
#r @"..\..\packages\FsUnit.1.3.0.1\Lib\Net40\FsUnit.NUnit.dll"
#r @"..\..\packages\Unquote.2.2.2\lib\net40\Unquote.dll"
#r @"..\..\packages\FsCheck.1.0.4\lib\net45\FsCheck.dll"
#r @"..\..\packages\NUnit.2.6.4\lib\nunit.framework.dll"
#r @"..\..\packages\FsCheck.Xunit.1.0.4\lib\net45\FsCheck.Xunit.dll"
#r @"..\..\packages\xunit.1.9.2\lib\net20\xunit.dll"